# Generated by Django 5.2.5 on 2025-10-04 14:45

import django.db.models.deletion
import docmind.utilities.process_and_query_rag
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(default='New Rag Session', max_length=255)),
                ('session_type', models.CharField(choices=[('RAG', 'RAG'), ('RESEARCH', 'RESEARCH')], default='RAG', max_length=25)),
                ('file', models.FileField(blank=True, null=True, upload_to=docmind.utilities.process_and_query_rag.pdf_upload_path)),
                ('index_dir', models.CharField(blank=True, max_length=1024)),
                ('embedding_model', models.CharField(default='thenlper/gte-small', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('User', 'User'), ('Assistant', 'Assistant')], default='User', max_length=25)),
                ('content', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
