# Generated by Django 5.2.7 on 2025-12-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_audio_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('RAG', 'RAG'), ('RESEARCH', 'RESEARCH'), ('DERMAI', 'DERMAI')], default='RAG', max_length=25),
        ),
    ]
