# Generated by Django 5.2.7 on 2025-12-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('RAG', 'RAG'), ('RESEARCH', 'RESEARCH'), ('DERMAI', 'DERMAI'), ('PSYCHAI', 'PSYCHAI')], default='RAG', max_length=25),
        ),
    ]
