# Generated by Django 5.2.5 on 2025-08-23 23:40

import docmind.utilities.process_and_query_rag
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragsession',
            name='embedding_model',
            field=models.CharField(default='sentence-transformers/all-MiniLM-L6-v2', max_length=200),
        ),
        migrations.AddField(
            model_name='ragsession',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=docmind.utilities.process_and_query_rag.pdf_upload_path),
        ),
        migrations.AddField(
            model_name='ragsession',
            name='index_dir',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
