# Generated by Django 5.2.5 on 2025-08-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmind', '0002_ragsession_embedding_model_ragsession_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragsession',
            name='embedding_model',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
