# Generated by Django 5.2.5 on 2025-08-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmind', '0003_alter_ragsession_embedding_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragsession',
            name='embedding_model',
            field=models.CharField(default='thenlper/gte-small', max_length=200),
        ),
    ]
