# Generated by Django 5.2.5 on 2025-09-28 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docmind', '0004_alter_ragsession_embedding_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RagMessage',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='RagSession',
            new_name='Session',
        ),
    ]
