# Generated by Django 5.2.5 on 2025-09-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmind', '0005_rename_ragmessage_message_rename_ragsession_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('RAG', 'RAG'), ('RESEARCH', 'RESEARCH')], default='RAG', max_length=25),
        ),
    ]
