# Generated by Django 5.2.5 on 2025-10-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docmind', '0006_session_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
